// Help: how to use the system, for project teams and for the administration. English and Arabic.
import { esc, ICON } from "../ui.js";
import { installApp, installAvailable, isStandalone } from "../pwa.js";
import { formRef } from "../settings.js";

const S = [
  { id: "app", who: "all",
    en: ["Install the app on your phone", `<ol><li>Open the system link on the phone: in <b>Chrome</b> on Android, in <b>Safari</b> on iPhone.</li><li>Android: tap <b>Install app</b> at the top of the page (or menu ⋮ → <b>Install app</b>).</li><li>iPhone: tap <b>Share</b> → <b>Add to Home Screen</b> → <b>Add</b>.</li><li>Open <b>HSE Audit</b> from the home screen. It is the same system with the same login and live data, full screen, and the camera opens straight from it.</li></ol><p><b>Android app file:</b> you can also <a href="downloads/HSE-Audit.apk" download>download HSE-Audit.apk</a> and install it like any app (allow installing from this source when Android asks). Reports you download in the app are saved in <b>Downloads › HSE Audit</b>.</p><p class="muted">The app needs mobile data or Wi-Fi to save. Without a connection you can open it and look, but nothing is saved until you are back online.</p>`],
    ar: ["تثبيت التطبيق على الموبايل", `<ol><li>افتح لينك السيستم على الموبايل: من <b>Chrome</b> على أندرويد، أو من <b>Safari</b> على الآيفون.</li><li>أندرويد: اضغط <b>Install app</b> أعلى الصفحة (أو القائمة ⋮ ← <b>Install app</b>).</li><li>آيفون: اضغط <b>Share</b> ← <b>Add to Home Screen</b> ← <b>Add</b>.</li><li>افتح <b>HSE Audit</b> من الشاشة الرئيسية. هو نفس السيستم بنفس الدخول ونفس البيانات، بيفتح full screen والكاميرا بتفتح منه مباشرة.</li></ol><p><b>أبلكيشن أندرويد:</b> تقدر كمان <a href="downloads/HSE-Audit.apk" download>تنزّل ملف HSE-Audit.apk</a> وتثبّته زي أي أبلكيشن (لو أندرويد سألك، اسمح بالتثبيت من المصدر ده). التقارير اللي بتنزّلها من الأبلكيشن بتتحفظ في <b>Downloads › HSE Audit</b>.</p><p class="muted">التطبيق محتاج نت (داتا أو Wi-Fi) علشان يحفظ. من غير نت تقدر تفتحه وتتفرج، لكن مفيش حاجة بتتحفظ لحد ما النت يرجع.</p>`] },
  { id: "signin", who: "all",
    en: ["Sign in", `<ul><li><b>Project team:</b> choose the <b>Project</b> tab, pick your project, type the project password and <b>your own name</b>. One password is shared by the project HSE team; your name is recorded with everything you do.</li><li><b>Administration:</b> choose the <b>Administration</b> tab and sign in with your e-mail and password, and your name.</li><li>Forgot the project password? Ask the administration to set a new one.</li></ul>`],
    ar: ["الدخول", `<ul><li><b>فريق المشروع:</b> اختار تبويب <b>Project</b>، واختار مشروعك، واكتب باسورد المشروع و<b>اسمك</b>. الباسورد واحد لفريق HSE في المشروع، واسمك بيتسجل مع كل حاجة بتعملها.</li><li><b>الإدارة:</b> اختار تبويب <b>Administration</b> وادخل بالإيميل والباسورد واسمك.</li><li>نسيت باسورد المشروع؟ اطلب من الإدارة تعمل باسورد جديد.</li></ul>`] },
  { id: "audit", who: "all",
    en: ["Do an audit on site with the checklist", `<ol><li>Tap <b>New audit</b>, check the date and details, then <b>Start checklist</b>.</li><li>Open a topic and mark every check <b>OK</b>, <b>NC</b> (not compliant) or <b>N/A</b>.</li><li>On <b>NC</b> a finding opens: write where and what you found, choose the risk, take the photo with <b>Camera</b>, pick the root cause.</li><li>Fixed on the spot? Choose <b>Yes</b>, write what was done and add the closure photo. If not, write the action, the owner and the target date.</li><li>Everything saves as you go. At the end tap <b>Finish &amp; submit</b>.</li></ol>`],
    ar: ["عمل أوديت في الموقع بالـ Checklist", `<ol><li>اضغط <b>New audit</b>، راجع التاريخ والبيانات، وبعدين <b>Start checklist</b>.</li><li>افتح كل topic وعلّم كل بند <b>OK</b> أو <b>NC</b> (مخالف) أو <b>N/A</b>.</li><li>لما تختار <b>NC</b> بتفتح ملاحظة: اكتب المكان واللي لقيته، اختار درجة الخطورة، صوّر بزرار <b>Camera</b>، واختار السبب الجذري.</li><li>اتصلحت في ساعتها؟ اختار <b>Yes</b> واكتب اللي اتعمل وضيف صورة الإقفال. لو لأ، اكتب الإجراء والمسؤول والتاريخ المستهدف.</li><li>كل حاجة بتتحفظ أول بأول. في الآخر اضغط <b>Finish &amp; submit</b>.</li></ol>`] },
  { id: "excel", who: "all",
    en: ["Import an Excel sheet", `<ol><li>Open <b>Import Excel report</b>${""} and choose the file (.xlsx).</li><li>The {FORM_EN} is read automatically.</li><li>Any other sheet works too: each finding on its own row, with the observation in one column. The system matches the columns by their headings (English or Arabic) — check the <b>Which column is which</b> box and correct anything.</li><li>Photos are matched to the row they sit on, whether floating on the sheet or placed inside the cell (Excel or WPS). A column headed <b>After</b>, <b>Closure</b> or <b>Evidence</b> is read as closure photos; you can change this per column.</li><li>Cell notes (comments) are added to the observation.</li><li>Check the table, untick rows you don't want, then <b>Import</b>.</li></ol>`],
    ar: ["رفع شيت Excel", `<ol><li>افتح <b>Import Excel report</b> واختار الملف (.xlsx).</li><li>{FORM_AR} بتتقري لوحدها.</li><li>أي شيت تاني بيشتغل برضه: كل ملاحظة في سطر لوحدها، والملاحظة في عمود واحد. السيستم بيتعرف على الأعمدة من عناوينها (عربي أو إنجليزي). راجع خانة <b>Which column is which</b> وصلّح أي حاجة.</li><li>الصور بتتربط بالسطر اللي هي عليه، سواء كانت على الشيت أو جوه الخلية (Excel أو WPS). العمود اللي عنوانه <b>After</b> أو <b>Closure</b> أو <b>بعد</b> بيتقري كصور إقفال، وتقدر تغيّر ده لكل عمود.</li><li>التعليقات (Notes) اللي على الخلايا بتتضاف للملاحظة.</li><li>راجع الجدول، شيل العلامة من أي سطر مش عايزه، واضغط <b>Import</b>.</li></ol>`] },
  { id: "close", who: "project",
    en: ["Close a finding", `<ol><li>Open the finding from the <b>Findings register</b> or the dashboard.</li><li>Under <b>Closure evidence</b> add the photo after the correction.</li><li>Write what was done in <b>Action taken</b> and tap <b>Submit closure for review</b>.</li><li>The finding shows <b>Pending review</b> until the administration approves it. If it comes back, read the comment, fix it and submit again.</li></ol>`],
    ar: ["إقفال ملاحظة", `<ol><li>افتح الملاحظة من <b>Findings register</b> أو من الـ Dashboard.</li><li>في <b>Closure evidence</b> ضيف صورة بعد التصحيح.</li><li>اكتب اللي اتعمل في <b>Action taken</b> واضغط <b>Submit closure for review</b>.</li><li>الملاحظة بتبقى <b>Pending review</b> لحد ما الإدارة توافق. لو رجعت، اقرا التعليق وصلّح وابعتها تاني.</li></ol>`] },
  { id: "review", who: "admin",
    en: ["Review closures", `<ol><li>Open the <b>Findings register</b> and set Status to <b>Pending review</b> (or click the figure on the dashboard).</li><li>Open each finding, look at the closure photo and the action.</li><li><b>Approve and close</b>, or <b>Return to project</b> with a reason — the reason is required and the project sees it.</li></ol>`],
    ar: ["مراجعة الإقفالات", `<ol><li>افتح <b>Findings register</b> واختار Status = <b>Pending review</b> (أو اضغط على الرقم في الـ Dashboard).</li><li>افتح كل ملاحظة وشوف صورة الإقفال والإجراء.</li><li><b>Approve and close</b> للموافقة، أو <b>Return to project</b> مع سبب، والسبب لازم يتكتب والمشروع بيشوفه.</li></ol>`] },
  { id: "projects", who: "admin",
    en: ["Projects and passwords", `<ul><li><b>Projects → Add project</b>, or <b>Import list from Excel</b> (columns: Project, Code, Location, Project Manager, Client).</li><li><b>Create logins</b> makes a password for every project without one and downloads them in an Excel file. Send each project only its own password.</li><li><b>Change password</b> on a project stops the old password at once.</li><li><b>Clear data</b> deletes a project's audits, findings and photos and keeps the project and its login. <b>Delete</b> removes the project completely.</li></ul>`],
    ar: ["المشاريع والباسوردات", `<ul><li><b>Projects ← Add project</b>، أو <b>Import list from Excel</b> (أعمدة: Project, Code, Location, Project Manager, Client).</li><li><b>Create logins</b> بيعمل باسورد لكل مشروع ملوش باسورد وينزّلهم في ملف Excel. ابعت لكل مشروع الباسورد بتاعه بس.</li><li><b>Change password</b> بيوقف الباسورد القديم فورًا.</li><li><b>Clear data</b> بيمسح أوديتات وملاحظات وصور المشروع ويسيب المشروع والباسورد. <b>Delete</b> بيمسح المشروع كله.</li></ul>`] },
  { id: "settings", who: "admin",
    en: ["Change the checklist and settings (no code)", `<ul><li><b>Settings → Checklist:</b> rename topics, edit, add, reorder or switch off checks, set the risk if not compliant, add whole topics, and add words that help the Excel import pick the topic. Press <b>Save checklist</b>. Old audits keep the checks they used.</li><li><b>Settings → Root causes:</b> the list auditors pick from.</li><li><b>Settings → Dashboard:</b> title, targets for closure rate and compliance, the period it opens with, and which charts show.</li><li><b>Settings → Reports &amp; names:</b> report title, form reference and revision, PowerPoint footer, and the system name in the top bar.</li></ul>`],
    ar: ["تعديل الـ Checklist والإعدادات (من غير كود)", `<ul><li><b>Settings ← Checklist:</b> غيّر أسماء الـ topics، عدّل أو ضيف أو رتّب أو وقّف بنود، حدد الخطورة لو مخالف، ضيف topics جديدة، وضيف كلمات بتساعد الـ Excel import يختار الـ topic. اضغط <b>Save checklist</b>. الأوديتات القديمة بتفضل بالبنود اللي اتعملت بيها.</li><li><b>Settings ← Root causes:</b> قائمة الأسباب اللي المراجع بيختار منها.</li><li><b>Settings ← Dashboard:</b> العنوان، الأهداف لنسبة الإقفال والالتزام، الفترة اللي بيفتح عليها، والرسومات اللي تظهر.</li><li><b>Settings ← Reports &amp; names:</b> عنوان التقرير، رقم الفورم والإصدار، الفوتر بتاع الـ PowerPoint، واسم السيستم في الشريط العلوي.</li></ul>`] },
  { id: "delete", who: "admin",
    en: ["Delete data", `<ul><li>In the <b>Findings register</b> or <b>Audits</b>, tick rows (or tick the box in the heading for everything in the filter) and press <b>Delete selected</b>.</li><li><b>Projects → Delete data…</b> deletes everything, one project, or audits between two dates. Type DELETE to confirm.</li><li>Deleting is permanent and removes the photos too. Download the register or reports first if you may need them.</li></ul>`],
    ar: ["مسح البيانات", `<ul><li>في <b>Findings register</b> أو <b>Audits</b> علّم على السطور (أو المربع في العنوان لكل اللي في الفلتر) واضغط <b>Delete selected</b>.</li><li><b>Projects ← Delete data…</b> بيمسح كل حاجة، أو مشروع واحد، أو أوديتات بين تاريخين. اكتب DELETE للتأكيد.</li><li>المسح نهائي وبيمسح الصور كمان. نزّل الـ Register أو التقارير الأول لو ممكن تحتاجها.</li></ul>`] },
  { id: "reports", who: "all",
    en: ["Dashboard and downloads", `<ul><li>The dashboard follows the filters at the top: period, location, project, audit type, risk, topic. Click a bar or a figure to open the findings behind it. Each chart has a <b>table</b> button.</li><li><b>PowerPoint</b> on the dashboard: a ready summary deck with editable charts. <b>Excel</b>: the same figures as a workbook.</li><li>On an audit: <b>{XLS_BTN}</b> (the corporate form with photos) or <b>PowerPoint</b> (one slide per observation, before and after photos).</li><li>The <b>Full screen</b> button hides the menus for meetings.</li></ul>`],
    ar: ["الـ Dashboard والتنزيلات", `<ul><li>الـ Dashboard بيمشي على الفلاتر اللي فوق: الفترة، الموقع، المشروع، نوع الأوديت، الخطورة، الـ topic. اضغط على أي رقم أو عمود يفتحلك الملاحظات اللي وراه. كل رسم فيه زرار <b>table</b>.</li><li><b>PowerPoint</b> من الـ Dashboard: ملخص جاهز برسومات تقدر تعدّلها. <b>Excel</b>: نفس الأرقام في ملف.</li><li>من صفحة أي أوديت: <b>{XLS_BTN}</b> (فورمة الشركة بالصور) أو <b>PowerPoint</b> (سلايد لكل ملاحظة بصورة قبل وبعد).</li><li>زرار <b>Full screen</b> بيخفي القوائم للعرض في الاجتماعات.</li></ul>`] },
  { id: "admins", who: "admin",
    en: ["Administrators", `<ul><li><b>Administrators → Add administrator</b> creates an e-mail login with full rights.</li><li>A shared review login is possible: everyone types their own name at sign-in, and the name is recorded. Change its password with the key icon when the review ends.</li></ul>`],
    ar: ["الأدمن", `<ul><li><b>Administrators ← Add administrator</b> بيعمل دخول بإيميل بصلاحيات كاملة.</li><li>ينفع إيميل مشترك للمراجعة: كل واحد بيكتب اسمه وهو بيدخل والاسم بيتسجل. غيّر الباسورد بتاعه من أيقونة المفتاح بعد المراجعة.</li></ul>`] },
  { id: "faq", who: "all",
    en: ["Questions", `<ul><li><b>A photo didn't upload.</b> Check the signal and add it again from the finding page.</li><li><b>I picked the wrong project.</b> Sign out (top right) and sign in again.</li><li><b>Who can see my project?</b> Only your project's login and the administration.</li><li><b>Something looks wrong.</b> Contact the system administrator with a screenshot.</li></ul>`],
    ar: ["أسئلة", `<ul><li><b>صورة ما اترفعتش.</b> اتأكد من النت وضيفها تاني من صفحة الملاحظة.</li><li><b>اخترت مشروع غلط.</b> اعمل Sign out (فوق على اليمين) وادخل تاني.</li><li><b>مين يشوف مشروعي؟</b> الدخول بتاع مشروعك والإدارة بس.</li><li><b>فيه حاجة شكلها غلط.</b> كلّم مسؤول السيستم وابعتله screenshot.</li></ul>`] },
];

export async function render(root, ctx) {
  const { isAdmin } = ctx;
  let lang = (() => { try { return localStorage.getItem("hse-audit:help-lang") || "en"; } catch (e) { return "en"; } })();
  const ref = esc(formRef());
  const fill = h => h.replace(/\{FORM_EN\}/g, ref ? `corporate <b>${ref}</b> form` : "corporate audit form")
    .replace(/\{FORM_AR\}/g, ref ? `فورمة الشركة <b>${ref}</b>` : "فورمة أوديت الشركة")
    .replace(/\{XLS_BTN\}/g, `Excel ${ref || "report"}`);
  const draw = () => {
    const list = S.filter(s => s.who === "all" || (s.who === "admin" ? isAdmin : !isAdmin) || (isAdmin && s.who === "project"));
    const ar = lang === "ar";
    root.innerHTML = `
      <div class="page-head"><div><h1>${ar ? "طريقة الاستخدام" : "How to use the system"}</h1><p class="muted">${isAdmin ? (ar ? "دليل الإدارة وفرق المشاريع" : "Guide for the administration and project teams") : (ar ? "دليل فريق المشروع" : "Guide for project teams")}</p></div>
        <div class="actions"><div class="seg period" role="group" aria-label="Language"><button type="button" data-lang="en" aria-pressed="${!ar}">English</button><button type="button" data-lang="ar" aria-pressed="${ar}">عربي</button></div>
        ${installAvailable() ? `<button class="btn primary" id="h-inst">${ICON.phone} ${ar ? "تثبيت التطبيق" : "Install the app"}</button>` : isStandalone() ? `<span class="pill ok">${ar ? "إنت فاتح التطبيق" : "You are using the app"}</span>` : ""}</div></div>
      <div class="help ${ar ? "rtl" : ""}" dir="${ar ? "rtl" : "ltr"}" lang="${ar ? "ar" : "en"}">
        <nav class="help-toc card">${list.map((s, i) => `<a href="#h-${s.id}" data-jump="${s.id}">${i + 1}. ${esc((ar ? s.ar : s.en)[0])}${s.who === "admin" ? ` <span class="tag admin">${ar ? "إدارة" : "Admin"}</span>` : ""}</a>`).join("")}</nav>
        <div class="help-body">${list.map((s, i) => `<section class="card help-sec" id="h-${s.id}"><h2>${i + 1}. ${esc((ar ? s.ar : s.en)[0])}${s.who === "admin" ? ` <span class="tag admin">${ar ? "إدارة" : "Admin"}</span>` : ""}</h2>${fill((ar ? s.ar : s.en)[1])}</section>`).join("")}</div>
      </div>`;
  };
  draw();
  root.addEventListener("click", e => {
    const l = e.target.closest("[data-lang]"); if (l) { lang = l.dataset.lang; try { localStorage.setItem("hse-audit:help-lang", lang); } catch (x) { /* ignore */ } draw(); return; }
    const j = e.target.closest("[data-jump]"); if (j) { e.preventDefault(); root.querySelector("#h-" + j.dataset.jump)?.scrollIntoView({ behavior: "smooth", block: "start" }); return; }
    if (e.target.closest("#h-inst")) installApp();
  });
}
